apiVersion: redis.cache.gzky.com/v1
kind: RedisCluster
metadata:
  labels:
    app.kubernetes.io/name: rediscluster
    app.kubernetes.io/instance: rediscluster-sample
    app.kubernetes.io/part-of: gzky-redis-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gzky-redis-operator
  name: rediscluster-sample
spec:
  masterNum: 3
  podTemplate:
    metadata:
      labels:
        redis-node: redis-node
    spec:
      initContainers:
      - name: redis-init
        image: harbor.gzky.com/devops-example/busybox:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        command:
          - /bin/sh
          - -c
          - |
            mkdir /redis-cluster/data /redis-cluster/conf
            cp /redis-conf/redis.conf /redis-cluster/conf/redis.conf
            sed "s/^bind.*$/bind $POD_IP/" -i /redis-cluster/conf/redis.conf
            #sysctl -w net.core.somaxconn=65536
        volumeMounts:
        - mountPath: /redis-conf
          name: conf
        - mountPath: /redis-cluster
          name: data
  
      containers:
      - args:
        - /redis-cluster/conf/redis.conf
        image: harbor.gzky.com/test/redis:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
        name: redis-node
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        - containerPort: 16379
          name: cluster
          protocol: TCP
        volumeMounts:
        - mountPath: /redis-cluster
          name: data
      volumes:
      - emptyDir: {}
        name: data
      - configMap:
          defaultMode: 420
          items:
          - key: redis.conf
            path: redis.conf
          name: rediscluster-sample
        name: conf
